export const enum ProductCategory {
  RAWMATERIAL = 'RAWMATERIAL',

  FINISHEDGOODS = 'FINISHEDGOODS',

  CONSUMABLE = 'CONSUMABLE',

  PACKINGMATERIAL = 'PACKINGMATERIAL',

  OFFICESUPPLIES = 'OFFICESUPPLIES',
}
