export const enum StockTransactionType {
  PURCHASE = 'PURCHASE',

  SALE = 'SALE',

  PRODUCTION = 'PRODUCTION',

  ADJUSTMENT = 'ADJUSTMENT',

  TRANSFORM = 'TRANSFORM',

  TRANSFER = 'TRANSFER',
}
